// Generated by CoffeeScript 1.10.0
(function() {
  var BubbleChart;

  BubbleChart = (function() {
    function BubbleChart(el, data, xTitle, yTitle) {
      this.el = el;
      this.data = data;
      this.xTitle = xTitle;
      this.yTitle = yTitle;
      this.margin = {
        top: 20,
        right: 20,
        bottom: 30,
        left: 50
      };
      this.width = $(this.el).width() - this.margin.left - this.margin.right;
      this.height = $(this.el).height() - this.margin.top - this.margin.bottom;
      this.color = d3.scale.category20c();
      this.r = 20;
      this.x = d3.scale.linear().range([0, this.width]).domain([
        0, (d3.max(this.data, function(d) {
          return d.value1;
        })) + this.r * 2
      ]);
      this.y = d3.scale.linear().range([this.height, 0]).domain([
        0, (d3.max(this.data, function(d) {
          return d.value2;
        })) + this.r * 2
      ]);
      this.xAxis = d3.svg.axis().scale(this.x).orient("bottom");
      this.yAxis = d3.svg.axis().scale(this.y).orient("left");
      this.svg = d3.select(this.el).append("svg").attr({
        width: this.width + this.margin.left + this.margin.right,
        height: this.height + this.margin.top + this.margin.bottom
      }).append("g").attr("transform", "translate(" + this.margin.left + ", " + this.margin.top + ")");
      this.svg.append("g").attr({
        "class": "x axis",
        transform: "translate(0, " + this.height + ")"
      }).call(this.xAxis).append("text").attr({
        x: this.width,
        y: -12,
        dx: ".71em"
      }).style("text-anchor", "end").text(this.xTitle);
      this.svg.append("g").attr("class", "y axis").call(this.yAxis).append("text").attr({
        transform: "rotate(-90)",
        y: 6,
        dy: ".71em"
      }).style("text-anchor", "end").text(this.yTitle);
      this.node = this.svg.selectAll(".node").data(this.data).enter().append("g").attr({
        "class": "node",
        transform: (function(_this) {
          return function(d) {
            return "translate(" + (_this.x(d.value1)) + ", " + (_this.y(d.value2)) + ")";
          };
        })(this)
      });
      this.node.append("title").text(function(d) {
        return d.name + " (" + d.value1 + ", " + d.value2 + ")";
      });
      this.node.append("circle").attr("r", (function(_this) {
        return function(d) {
          return _this.r;
        };
      })(this)).style("fill", (function(_this) {
        return function(d) {
          return _this.color(d.name);
        };
      })(this));
      this.node.append("text").attr("dy", ".3em").style("text-anchor", "middle").text(function(d) {
        return d.name;
      });
    }

    return BubbleChart;

  })();

  window.BubbleChart = BubbleChart;

}).call(this);
