// Generated by CoffeeScript 1.10.0
(function() {
  var LineChart;

  LineChart = (function() {
    function LineChart(el, data) {
      var line;
      this.el = el;
      this.data = data;
      this.margin = {
        top: 20,
        right: 20,
        bottom: 30,
        left: 50
      };
      this.width = $(this.el).width() - this.margin.left - this.margin.right;
      this.height = $(this.el).height() - this.margin.top - this.margin.bottom;
      this.x = d3.time.scale().range([0, this.width]);
      this.y = d3.scale.linear().range([this.height, 0]);
      this.xAxis = d3.svg.axis().scale(this.x).orient("bottom").tickFormat(d3.time.format("%d"));
      this.yAxis = d3.svg.axis().scale(this.y).orient("left");
      line = d3.svg.line().x((function(_this) {
        return function(d) {
          return _this.x(d.date);
        };
      })(this)).y((function(_this) {
        return function(d) {
          return _this.y(d.value);
        };
      })(this));
      this.svg = d3.select(this.el).append("svg").attr({
        width: this.width + this.margin.left + this.margin.right,
        height: this.height + this.margin.top + this.margin.bottom
      }).append("g").attr("transform", "translate(" + this.margin.left + ", " + this.margin.top + ")");
      this.x.domain(d3.extent(this.data, function(d) {
        return d.date;
      }));
      this.y.domain(d3.extent(this.data, function(d) {
        return d.value;
      }));
      this.svg.append("g").attr({
        "class": "x axis",
        transform: "translate(0, " + this.height + ")"
      }).call(this.xAxis);
      this.svg.append("g").attr("class", "y axis").call(this.yAxis).append("text").attr({
        transform: "rotate(-90)",
        y: 6,
        dy: ".71em"
      }).style("text-anchor", "end").text("pv (次数)");
      this.svg.append("path").datum(this.data).attr({
        "class": "line",
        "d": line
      });
    }

    return LineChart;

  })();

  window.LineChart = LineChart;

}).call(this);
