// Generated by CoffeeScript 1.10.0
(function() {
  var TreeMap;

  TreeMap = (function() {
    function TreeMap(el, data) {
      this.el = el;
      this.data = data;
      this.margin = {
        top: 40,
        right: 10,
        bottom: 10,
        left: 10
      };
      this.width = $(this.el).width() - this.margin.left - this.margin.right;
      this.height = $(this.el).height() - this.margin.top - this.margin.bottom;
      this.color = d3.scale.category20c();
      this.treemap = d3.layout.treemap().size([this.width, this.height]).sticky(true).value(function(d) {
        return d.size;
      });
      this.div = d3.select(this.el).append("div").style({
        "position": "relative",
        "width": this.width + "px",
        "height": this.height + "px",
        "left": this.margin.left + "px",
        "top": this.margin.top + "px"
      });
      this.node = this.div.datum(this.data).selectAll(".node").data(this.treemap.nodes).enter().append("div").attr("class", "node").call(this.position).style("background", (function(_this) {
        return function(d) {
          if (d.children) {
            return _this.color(d.name);
          } else {
            return null;
          }
        };
      })(this)).text(function(d) {
        if (d.children) {
          return null;
        } else {
          return d.name;
        }
      });
    }

    TreeMap.prototype.position = function() {
      return this.style({
        left: function(d) {
          return d.x + "px";
        },
        top: function(d) {
          return d.y + "px";
        },
        width: function(d) {
          return Math.max(0, d.dx - 1) + "px";
        },
        height: function(d) {
          return Math.max(0, d.dy - 1) + "px";
        }
      });
    };

    TreeMap.prototype.dimension_changed = function(valFn) {
      return this.node.data(this.treemap.value(valFn).nodes).transition().duration(1500).call(this.position);
    };

    return TreeMap;

  })();

  window.TreeMap = TreeMap;

}).call(this);
